export const designTokens = {
  colors: {
    page: '#EFE5D2',
    ink: '#000000',
    inkSoft: '#0D0D0D',
    brandWine: '#480C1D',
    logoWine: '#220C12',
    textMuted: '#616161',
    textMutedAlt: '#626262',
    textSoft: '#7F7575',
    borderLight: '#DADADA',
    white: '#FFFFFF',
    black: '#000000',
    greyMeta: '#C4C4C4',
  },
  fonts: {
    brand: '"Bodoni Moda", Didot, "Times New Roman", serif',
    display: '"Mona Sans", Inter, Arial, sans-serif',
    sans: '"Mona Sans", Inter, Arial, sans-serif',
    meta: '"Mona Sans", Montserrat, Arial, sans-serif',
  },
  layout: {
    desktopCanvas: 1440,
    mobileCanvas: 390,
    desktopMargin: 118,
    desktopRuleInset: 20,
    mobileMargin: 16,
    contentMax: 1204,
  },
  breakpoints: {
    mobile: 390,
    tablet: 768,
    desktop: 1024,
    figmaDesktop: 1440,
  },
  spacing: {
    xs: 5,
    sm: 10,
    md: 20,
    lg: 40,
    xl: 59,
    carousel: 82,
    reelGap: 92,
  },
  radii: {
    image: 10,
    button: 10,
    card: 10,
  },
};
